//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallContext", Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
    public partial class CallContext : object
    {
        
        private string CompanyField;
        
        private string LanguageField;
        
        private string LogonAsUserField;
        
        private string MessageIdField;
        
        private string PartitionKeyField;
        
        private System.Collections.Generic.Dictionary<string, string> PropertyBagField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company
        {
            get
            {
                return this.CompanyField;
            }
            set
            {
                this.CompanyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language
        {
            get
            {
                return this.LanguageField;
            }
            set
            {
                this.LanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogonAsUser
        {
            get
            {
                return this.LogonAsUserField;
            }
            set
            {
                this.LogonAsUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId
        {
            get
            {
                return this.MessageIdField;
            }
            set
            {
                this.MessageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartitionKey
        {
            get
            {
                return this.PartitionKeyField;
            }
            set
            {
                this.PartitionKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> PropertyBag
        {
            get
            {
                return this.PropertyBagField;
            }
            set
            {
                this.PropertyBagField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XppObjectBase", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.Ax.Xpp")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventJournalTableDataContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventJournalTransDataContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventJournalTablePagedDataContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventJournalTransPagedDataContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKServiceResponseDataContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventJournalCreateDataContract))]
    public partial class XppObjectBase : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GMKInventJournalTableDataContract", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public partial class GMKInventJournalTableDataContract : InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.XppObjectBase
    {
        
        private string CreatedByField;
        
        private string DescriptionField;
        
        private InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventJournalTransDataContract[] InventJournalTransField;
        
        private string JournalIdField;
        
        private string JournalNameIdField;
        
        private int NumOfLinesField;
        
        private InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.NoYes PostedField;
        
        private string PostedUserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventJournalTransDataContract[] InventJournalTrans
        {
            get
            {
                return this.InventJournalTransField;
            }
            set
            {
                this.InventJournalTransField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JournalId
        {
            get
            {
                return this.JournalIdField;
            }
            set
            {
                this.JournalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JournalNameId
        {
            get
            {
                return this.JournalNameIdField;
            }
            set
            {
                this.JournalNameIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfLines
        {
            get
            {
                return this.NumOfLinesField;
            }
            set
            {
                this.NumOfLinesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.NoYes Posted
        {
            get
            {
                return this.PostedField;
            }
            set
            {
                this.PostedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostedUserId
        {
            get
            {
                return this.PostedUserIdField;
            }
            set
            {
                this.PostedUserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GMKInventJournalTransDataContract", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public partial class GMKInventJournalTransDataContract : InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.XppObjectBase
    {
        
        private decimal CountedField;
        
        private string InventBatchIdField;
        
        private string InventLocationIdField;
        
        private decimal InventOnHandField;
        
        private string InventSiteIdField;
        
        private string ItemIdField;
        
        private string ItemNameField;
        
        private string JournalIdField;
        
        private decimal QtyField;
        
        private System.DateTime TransDateField;
        
        private string UnitIdField;
        
        private string WMSLocationIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Counted
        {
            get
            {
                return this.CountedField;
            }
            set
            {
                this.CountedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InventBatchId
        {
            get
            {
                return this.InventBatchIdField;
            }
            set
            {
                this.InventBatchIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InventLocationId
        {
            get
            {
                return this.InventLocationIdField;
            }
            set
            {
                this.InventLocationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal InventOnHand
        {
            get
            {
                return this.InventOnHandField;
            }
            set
            {
                this.InventOnHandField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InventSiteId
        {
            get
            {
                return this.InventSiteIdField;
            }
            set
            {
                this.InventSiteIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemId
        {
            get
            {
                return this.ItemIdField;
            }
            set
            {
                this.ItemIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemName
        {
            get
            {
                return this.ItemNameField;
            }
            set
            {
                this.ItemNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JournalId
        {
            get
            {
                return this.JournalIdField;
            }
            set
            {
                this.JournalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Qty
        {
            get
            {
                return this.QtyField;
            }
            set
            {
                this.QtyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TransDate
        {
            get
            {
                return this.TransDateField;
            }
            set
            {
                this.TransDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitId
        {
            get
            {
                return this.UnitIdField;
            }
            set
            {
                this.UnitIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WMSLocationId
        {
            get
            {
                return this.WMSLocationIdField;
            }
            set
            {
                this.WMSLocationIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GMKInventJournalTablePagedDataContract", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public partial class GMKInventJournalTablePagedDataContract : InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.XppObjectBase
    {
        
        private InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventJournalTableDataContract[] ItemsField;
        
        private int PageNumberField;
        
        private int PageSizeField;
        
        private int TotalCountField;
        
        private int TotalPagesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventJournalTableDataContract[] Items
        {
            get
            {
                return this.ItemsField;
            }
            set
            {
                this.ItemsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageNumber
        {
            get
            {
                return this.PageNumberField;
            }
            set
            {
                this.PageNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize
        {
            get
            {
                return this.PageSizeField;
            }
            set
            {
                this.PageSizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalCount
        {
            get
            {
                return this.TotalCountField;
            }
            set
            {
                this.TotalCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalPages
        {
            get
            {
                return this.TotalPagesField;
            }
            set
            {
                this.TotalPagesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GMKInventJournalTransPagedDataContract", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public partial class GMKInventJournalTransPagedDataContract : InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.XppObjectBase
    {
        
        private InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventJournalTransDataContract[] ItemsField;
        
        private int PageNumberField;
        
        private int PageSizeField;
        
        private int TotalCountField;
        
        private int TotalPagesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventJournalTransDataContract[] Items
        {
            get
            {
                return this.ItemsField;
            }
            set
            {
                this.ItemsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageNumber
        {
            get
            {
                return this.PageNumberField;
            }
            set
            {
                this.PageNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize
        {
            get
            {
                return this.PageSizeField;
            }
            set
            {
                this.PageSizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalCount
        {
            get
            {
                return this.TotalCountField;
            }
            set
            {
                this.TotalCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalPages
        {
            get
            {
                return this.TotalPagesField;
            }
            set
            {
                this.TotalPagesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GMKServiceResponseDataContract", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public partial class GMKServiceResponseDataContract : InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.XppObjectBase
    {
        
        private string MessageField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GMKInventJournalCreateDataContract", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public partial class GMKInventJournalCreateDataContract : InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.XppObjectBase
    {
        
        private string InventBatchIdField;
        
        private string InventLocationIdField;
        
        private string InventSiteIdField;
        
        private string SlsNoField;
        
        private string WMSLocationIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InventBatchId
        {
            get
            {
                return this.InventBatchIdField;
            }
            set
            {
                this.InventBatchIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InventLocationId
        {
            get
            {
                return this.InventLocationIdField;
            }
            set
            {
                this.InventLocationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InventSiteId
        {
            get
            {
                return this.InventSiteIdField;
            }
            set
            {
                this.InventSiteIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SlsNo
        {
            get
            {
                return this.SlsNoField;
            }
            set
            {
                this.SlsNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WMSLocationId
        {
            get
            {
                return this.WMSLocationIdField;
            }
            set
            {
                this.WMSLocationIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NoYes", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.Ax.Xpp")]
    public enum NoYes : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        No = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Yes = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class AifFault : object
    {
        
        private string CustomDetailXmlField;
        
        private InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.FaultMessageList[] FaultMessageListArrayField;
        
        private InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.InfologMessage[] InfologMessageListField;
        
        private string StackTraceField;
        
        private int XppExceptionTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomDetailXml
        {
            get
            {
                return this.CustomDetailXmlField;
            }
            set
            {
                this.CustomDetailXmlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.FaultMessageList[] FaultMessageListArray
        {
            get
            {
                return this.FaultMessageListArrayField;
            }
            set
            {
                this.FaultMessageListArrayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.InfologMessage[] InfologMessageList
        {
            get
            {
                return this.InfologMessageListField;
            }
            set
            {
                this.InfologMessageListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace
        {
            get
            {
                return this.StackTraceField;
            }
            set
            {
                this.StackTraceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int XppExceptionType
        {
            get
            {
                return this.XppExceptionTypeField;
            }
            set
            {
                this.XppExceptionTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessageList", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessageList : object
    {
        
        private string DocumentField;
        
        private string DocumentOperationField;
        
        private InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.FaultMessage[] FaultMessageArrayField;
        
        private string FieldField;
        
        private string ServiceField;
        
        private string ServiceOperationField;
        
        private string ServiceOperationParameterField;
        
        private string XPathField;
        
        private string XmlLineField;
        
        private string XmlPositionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Document
        {
            get
            {
                return this.DocumentField;
            }
            set
            {
                this.DocumentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentOperation
        {
            get
            {
                return this.DocumentOperationField;
            }
            set
            {
                this.DocumentOperationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.FaultMessage[] FaultMessageArray
        {
            get
            {
                return this.FaultMessageArrayField;
            }
            set
            {
                this.FaultMessageArrayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Field
        {
            get
            {
                return this.FieldField;
            }
            set
            {
                this.FieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Service
        {
            get
            {
                return this.ServiceField;
            }
            set
            {
                this.ServiceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperation
        {
            get
            {
                return this.ServiceOperationField;
            }
            set
            {
                this.ServiceOperationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperationParameter
        {
            get
            {
                return this.ServiceOperationParameterField;
            }
            set
            {
                this.ServiceOperationParameterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XPath
        {
            get
            {
                return this.XPathField;
            }
            set
            {
                this.XPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlLine
        {
            get
            {
                return this.XmlLineField;
            }
            set
            {
                this.XmlLineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlPosition
        {
            get
            {
                return this.XmlPositionField;
            }
            set
            {
                this.XmlPositionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessage", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public partial class InfologMessage : object
    {
        
        private InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.InfologMessageType InfologMessageTypeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.InfologMessageType InfologMessageType
        {
            get
            {
                return this.InfologMessageTypeField;
            }
            set
            {
                this.InfologMessageTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessage", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessage : object
    {
        
        private string CodeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessageType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public enum InfologMessageType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventory" +
        "ManagementService")]
    public interface GMKInventoryManagementService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GMKInventoryManagementService/createCountingJournal", ReplyAction="http://tempuri.org/GMKInventoryManagementService/createCountingJournalResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.AifFault), Action="http://tempuri.org/GMKInventoryManagementService/createCountingJournalAifFaultFau" +
            "lt", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementServiceCreateCountingJournalResponse> createCountingJournalAsync(InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementServiceCreateCountingJournalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GMKInventoryManagementService/getInventJournalTable", ReplyAction="http://tempuri.org/GMKInventoryManagementService/getInventJournalTableResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.AifFault), Action="http://tempuri.org/GMKInventoryManagementService/getInventJournalTableAifFaultFau" +
            "lt", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementServiceGetInventJournalTableResponse> getInventJournalTableAsync(InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementServiceGetInventJournalTableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GMKInventoryManagementService/getInventJournalTrans", ReplyAction="http://tempuri.org/GMKInventoryManagementService/getInventJournalTransResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.AifFault), Action="http://tempuri.org/GMKInventoryManagementService/getInventJournalTransAifFaultFau" +
            "lt", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementServiceGetInventJournalTransResponse> getInventJournalTransAsync(InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementServiceGetInventJournalTransRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GMKInventoryManagementService/getInventJournalTransPaged", ReplyAction="http://tempuri.org/GMKInventoryManagementService/getInventJournalTransPagedRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.AifFault), Action="http://tempuri.org/GMKInventoryManagementService/getInventJournalTransPagedAifFau" +
            "ltFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementServiceGetInventJournalTransPagedResponse> getInventJournalTransPagedAsync(InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementServiceGetInventJournalTransPagedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GMKInventoryManagementService/getInventJournalTablePaged", ReplyAction="http://tempuri.org/GMKInventoryManagementService/getInventJournalTablePagedRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.AifFault), Action="http://tempuri.org/GMKInventoryManagementService/getInventJournalTablePagedAifFau" +
            "ltFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementServiceGetInventJournalTablePagedResponse> getInventJournalTablePagedAsync(InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementServiceGetInventJournalTablePagedRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GMKInventoryManagementServiceCreateCountingJournalRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class GMKInventoryManagementServiceCreateCountingJournalRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventJournalCreateDataContract parm;
        
        public GMKInventoryManagementServiceCreateCountingJournalRequest()
        {
        }
        
        public GMKInventoryManagementServiceCreateCountingJournalRequest(InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.CallContext CallContext, InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventJournalCreateDataContract parm)
        {
            this.CallContext = CallContext;
            this.parm = parm;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GMKInventoryManagementServiceCreateCountingJournalResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class GMKInventoryManagementServiceCreateCountingJournalResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKServiceResponseDataContract response;
        
        public GMKInventoryManagementServiceCreateCountingJournalResponse()
        {
        }
        
        public GMKInventoryManagementServiceCreateCountingJournalResponse(InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKServiceResponseDataContract response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GMKInventoryManagementServiceGetInventJournalTableRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class GMKInventoryManagementServiceGetInventJournalTableRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string journalId;
        
        public GMKInventoryManagementServiceGetInventJournalTableRequest()
        {
        }
        
        public GMKInventoryManagementServiceGetInventJournalTableRequest(InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.CallContext CallContext, string journalId)
        {
            this.CallContext = CallContext;
            this.journalId = journalId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GMKInventoryManagementServiceGetInventJournalTableResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class GMKInventoryManagementServiceGetInventJournalTableResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventJournalTableDataContract response;
        
        public GMKInventoryManagementServiceGetInventJournalTableResponse()
        {
        }
        
        public GMKInventoryManagementServiceGetInventJournalTableResponse(InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventJournalTableDataContract response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GMKInventoryManagementServiceGetInventJournalTransRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class GMKInventoryManagementServiceGetInventJournalTransRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string inventTransId;
        
        public GMKInventoryManagementServiceGetInventJournalTransRequest()
        {
        }
        
        public GMKInventoryManagementServiceGetInventJournalTransRequest(InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.CallContext CallContext, string inventTransId)
        {
            this.CallContext = CallContext;
            this.inventTransId = inventTransId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GMKInventoryManagementServiceGetInventJournalTransResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class GMKInventoryManagementServiceGetInventJournalTransResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventJournalTransDataContract response;
        
        public GMKInventoryManagementServiceGetInventJournalTransResponse()
        {
        }
        
        public GMKInventoryManagementServiceGetInventJournalTransResponse(InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventJournalTransDataContract response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GMKInventoryManagementServiceGetInventJournalTransPagedRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class GMKInventoryManagementServiceGetInventJournalTransPagedRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public int pageNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public int pageSize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventJournalTransDataContract parm;
        
        public GMKInventoryManagementServiceGetInventJournalTransPagedRequest()
        {
        }
        
        public GMKInventoryManagementServiceGetInventJournalTransPagedRequest(InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.CallContext CallContext, int pageNumber, int pageSize, InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventJournalTransDataContract parm)
        {
            this.CallContext = CallContext;
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
            this.parm = parm;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GMKInventoryManagementServiceGetInventJournalTransPagedResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class GMKInventoryManagementServiceGetInventJournalTransPagedResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventJournalTransPagedDataContract response;
        
        public GMKInventoryManagementServiceGetInventJournalTransPagedResponse()
        {
        }
        
        public GMKInventoryManagementServiceGetInventJournalTransPagedResponse(InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventJournalTransPagedDataContract response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GMKInventoryManagementServiceGetInventJournalTablePagedRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class GMKInventoryManagementServiceGetInventJournalTablePagedRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public int pageNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public int pageSize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventJournalTableDataContract parm;
        
        public GMKInventoryManagementServiceGetInventJournalTablePagedRequest()
        {
        }
        
        public GMKInventoryManagementServiceGetInventJournalTablePagedRequest(InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.CallContext CallContext, int pageNumber, int pageSize, InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventJournalTableDataContract parm)
        {
            this.CallContext = CallContext;
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
            this.parm = parm;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GMKInventoryManagementServiceGetInventJournalTablePagedResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class GMKInventoryManagementServiceGetInventJournalTablePagedResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventJournalTablePagedDataContract response;
        
        public GMKInventoryManagementServiceGetInventJournalTablePagedResponse()
        {
        }
        
        public GMKInventoryManagementServiceGetInventJournalTablePagedResponse(InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventJournalTablePagedDataContract response)
        {
            this.response = response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface GMKInventoryManagementServiceChannel : InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class GMKInventoryManagementServiceClient : System.ServiceModel.ClientBase<InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementService>, InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public GMKInventoryManagementServiceClient() : 
                base(GMKInventoryManagementServiceClient.GetDefaultBinding(), GMKInventoryManagementServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.NetTcpBinding_GMKInventoryManagementService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GMKInventoryManagementServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(GMKInventoryManagementServiceClient.GetBindingForEndpoint(endpointConfiguration), GMKInventoryManagementServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GMKInventoryManagementServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(GMKInventoryManagementServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GMKInventoryManagementServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(GMKInventoryManagementServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GMKInventoryManagementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementServiceCreateCountingJournalResponse> InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementService.createCountingJournalAsync(InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementServiceCreateCountingJournalRequest request)
        {
            return base.Channel.createCountingJournalAsync(request);
        }
        
        public System.Threading.Tasks.Task<InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementServiceCreateCountingJournalResponse> createCountingJournalAsync(InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.CallContext CallContext, InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventJournalCreateDataContract parm)
        {
            InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementServiceCreateCountingJournalRequest inValue = new InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementServiceCreateCountingJournalRequest();
            inValue.CallContext = CallContext;
            inValue.parm = parm;
            return ((InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementService)(this)).createCountingJournalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementServiceGetInventJournalTableResponse> InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementService.getInventJournalTableAsync(InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementServiceGetInventJournalTableRequest request)
        {
            return base.Channel.getInventJournalTableAsync(request);
        }
        
        public System.Threading.Tasks.Task<InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementServiceGetInventJournalTableResponse> getInventJournalTableAsync(InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.CallContext CallContext, string journalId)
        {
            InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementServiceGetInventJournalTableRequest inValue = new InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementServiceGetInventJournalTableRequest();
            inValue.CallContext = CallContext;
            inValue.journalId = journalId;
            return ((InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementService)(this)).getInventJournalTableAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementServiceGetInventJournalTransResponse> InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementService.getInventJournalTransAsync(InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementServiceGetInventJournalTransRequest request)
        {
            return base.Channel.getInventJournalTransAsync(request);
        }
        
        public System.Threading.Tasks.Task<InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementServiceGetInventJournalTransResponse> getInventJournalTransAsync(InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.CallContext CallContext, string inventTransId)
        {
            InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementServiceGetInventJournalTransRequest inValue = new InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementServiceGetInventJournalTransRequest();
            inValue.CallContext = CallContext;
            inValue.inventTransId = inventTransId;
            return ((InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementService)(this)).getInventJournalTransAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementServiceGetInventJournalTransPagedResponse> InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementService.getInventJournalTransPagedAsync(InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementServiceGetInventJournalTransPagedRequest request)
        {
            return base.Channel.getInventJournalTransPagedAsync(request);
        }
        
        public System.Threading.Tasks.Task<InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementServiceGetInventJournalTransPagedResponse> getInventJournalTransPagedAsync(InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.CallContext CallContext, int pageNumber, int pageSize, InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventJournalTransDataContract parm)
        {
            InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementServiceGetInventJournalTransPagedRequest inValue = new InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementServiceGetInventJournalTransPagedRequest();
            inValue.CallContext = CallContext;
            inValue.pageNumber = pageNumber;
            inValue.pageSize = pageSize;
            inValue.parm = parm;
            return ((InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementService)(this)).getInventJournalTransPagedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementServiceGetInventJournalTablePagedResponse> InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementService.getInventJournalTablePagedAsync(InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementServiceGetInventJournalTablePagedRequest request)
        {
            return base.Channel.getInventJournalTablePagedAsync(request);
        }
        
        public System.Threading.Tasks.Task<InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementServiceGetInventJournalTablePagedResponse> getInventJournalTablePagedAsync(InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.CallContext CallContext, int pageNumber, int pageSize, InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventJournalTableDataContract parm)
        {
            InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementServiceGetInventJournalTablePagedRequest inValue = new InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementServiceGetInventJournalTablePagedRequest();
            inValue.CallContext = CallContext;
            inValue.pageNumber = pageNumber;
            inValue.pageSize = pageSize;
            inValue.parm = parm;
            return ((InventoryManagementSystem.Service.GMKInventoryManagementServiceGroup.GMKInventoryManagementService)(this)).getInventJournalTablePagedAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_GMKInventoryManagementService))
            {
                System.ServiceModel.NetTcpBinding result = new System.ServiceModel.NetTcpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_GMKInventoryManagementService))
            {
                return new System.ServiceModel.EndpointAddress("net.tcp://ead-lab:8201/DynamicsAx/Services/GMKInventoryManagementServiceGroup");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return GMKInventoryManagementServiceClient.GetBindingForEndpoint(EndpointConfiguration.NetTcpBinding_GMKInventoryManagementService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return GMKInventoryManagementServiceClient.GetEndpointAddress(EndpointConfiguration.NetTcpBinding_GMKInventoryManagementService);
        }
        
        public enum EndpointConfiguration
        {
            
            NetTcpBinding_GMKInventoryManagementService,
        }
    }
}
